name: Continuous cd

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: adding aws credentials
        run: sed -i 's|"cqube_db_host"|"${{secrets.DB_HOST}}"|g;s|"cqube_db_port"|"${{secrets.DB_PORT}}"|g;s|"cqube_database"|"${{secrets.DATABASE}}"|g;s|"cqube_db_user"|"${{secrets.DB_USER}}"|g;s|"cqube_db_password"|"${{secrets.DB_PASSWORD}}"|g' config.ini
        shell: bash
      - name: adding   
        run: cat config.ini
        
        shell: bash

